### ISSUE TITLE
Rozwijanie dokumentacji

### ISSUE THREAD

**Issue by mpfmorawski** [mpfmorawski/git-to-know-me#11]
Jest to issue do informowania, co zostało opracowane i można to dodać do dokumentacji

**Comment by pktiuk** [comment]
Z mojej strony nie mam nic do dodania w kontekście dokumentacji.  
Jeśli w jakiś szczególny sposób rozwinę routing wewnątrz aplikacji to będzie można opisać ten aspekt.

**Comment by KarolNiem** [comment]
Z małych uwag to w nazwie 4 rozdziału jest błąd. Powinno być ,,projekt interfejsu graficznego''. A tak poza tym to merytorycznie wydaje się być ok.

**Comment by jprokopczuk** [comment]
Na obecną chwilę zminił się endpoint fetchera `/github/stats/general_user/ ` zmieniony jest na `/github/stats/{user_name}`.

**Comment by mpfmorawski** [comment]
Notatka ze spotkania 06.05.2022:

Ewentualnie można wspomnieć o routingu w postaci akapitu w tekście

**Comment by lapankrz** [comment]
Dodanie info o konfiguracji Nginx - nasłuchiwanie na porcie 8000 requestów od użytkownika, komunikacja międzyserwisowowa na portach 8001-8004 (dokładniej opisane w folderze common np. na branchu multiproc)

**Comment by pktiuk** [comment]
Możesz dopisać w dokumentacji akapit poświęcony bezpieczeństwu.  
Można tu podkreślić takie aspekty jak:  
- architekturę separującą wewnętrzne api, tylko endpointy `/api/...` są osiągalne
- dodanie ochrony przeciwko cross site (jakieś szczegóły może opisać @kamilwil )
- wykorzystanie protokołu https przy deploymencie
- możliwe wykorzystanie proxy od cloudflare'a, które pozwala zapobiegać atakom DDOS (też aspekt deploymentowy)

Tak btw to robiąć deployment przez CF możemy też monitorować pewne aspekty ruchu naszej strony
![image](https://user-images.githubusercontent.com/45544416/169359214-4af58b0e-6718-41ec-a45d-9db5a3b08d78.png)

**Comment by mpfmorawski** [comment]
Uzupełniłem dokumentację na podstawie sugestii.

Plik z aktualną dokumentacją: [DOKUMENTACJA - 31.05.2022](https://github.com/mpfmorawski/git-to-know-me/files/8806104/DOKUMENTACJA.-.31.05.2022.pdf)

Kolejne aktualizacje dokumentacji będą umieszczane w #32
