### ISSUE TITLE
Uzupełnienie kafelka placeholdera oraz dodanie kafelków z językami oraz listą repozytoriów

### ISSUE THREAD

**Issue by mpfmorawski** [mpfmorawski/git-to-know-me#17]
**Kafelki:**
- [x] sumaryczne statystyki: łączna liczba repo, gwiazdek i forków (wypełnić placeholder)
- [x] wykres kołowy z procentowym sumarycznyn udziałem języków programowania
- [x] lista 5 repozytoriów, w każdym z nich wyszczególniona liczba gwiazdek, forków, watchów i kontrybutorów
- [x] przełącznik trybu sortowania (najpopularniejsze/ostatnio aktywne/z największym wkładem)

**Funkcjonalności:**
- ~~resize dla landing page'a (dodanie bounding boxa, żeby się strona zawsze skalowała)~~
- ~~obsługa anulowania udzielenia autoryzacji~~
- [x] sortowanie listy 5 repo na trzy sposoby (patrz wyżej)
- ~~skalowanie grida z przełączaniem się do jednej kolumny poniżej pewnej szerokości ekranu (mobile)~~
- [x] obsługa wyświetlania awatara usera (zastąpić placeholdery)

Przekreślone punkty przeniesione do #35

**Comment by kamilwil** [comment]
> obsługa anulowania udzielenia autoryzacji

Ustaliliśmy wczoraj z @lapankrz, że teoretycznie można by obejść się bez tego, ale proponuję ustalić to ostatecznie w całym zespole na jutrzejszym spotkaniu (2 czerwca).

**Comment by kamilwil** [comment]
Z powyższego ostatecznie zrezygnowaliśmy na spotkaniu 2 czerwca.

Postępy zostały wdrożone do `main` w ramach #30
