### ISSUE TITLE
Zapewnienie ochrony przed Cross Site Scripting (XSS)

### ISSUE THREAD

**Issue by mpfmorawski** [mpfmorawski/git-to-know-me#34]

**Comment by kamilwil** [comment]
Podstawową odporność na ataki typu XSS jest brak jakichkolwiek pól tekstowych lub innych kontrolek, w których użytkownik mógłby wpisać dowolną treść. Nie mamy także żadnych formularzy i nic nie leci przez POST. Po stronie frontu nie korzystamy też z querystringów w URL (czyli tych wszystkich dopisków w stylu `page?key=value`), bo zapytania do API GitHuba są wysyłane z serwisów ukrytych za endpointami `/api`.

Szczególnie dobrze pomyśleliśmy o tym w kontekście logowania - oddelegowując wpisywanie loginu i hasła do zewnętrznej usługi (tu: GitHub) pozbyliśmy się tego problemu po naszej stronie.

Inputy, formularze, POST i querystringi - to te były najczęściej przytaczane jako elementy, na które trzeba uważać w kontekście XSS. W tej sytuacji nie mam pomysłu, co jeszcze mogłoby być podatnością na XSS u nas. Jeśli nikt inny (szczególnie @lapankrz) też nie ma pomysłu, to chyba możemy uznać, że mamy ochronę przed atakami typu XSS, a ten issue zamknąć.

**Comment by mpfmorawski** [comment]
Dzięki za opis, zamykam
