### ISSUE TITLE
Dodanie Github Actions

### ISSUE THREAD

**Issue by mpfmorawski** [mpfmorawski/git-to-know-me#6]
- [x] Sprawdzenie formatowania plików py poprzez Github Actions

**Comment by KarolNiem** [comment]
Dodałem do naszego repozytorium folder `.github/workflows`, w którym umieściłem plik `autoyapf.yml`. Ma on za zadanie sprawdzanie formatowania kodu w plikach `.py` i ewentualną poprawę formatowania za każdym razem kiedy któryś z nich jest pushowany do maina. Kod testowałem na innym repozytorium i działał

**Comment by mpfmorawski** [comment]
@KarolNiem, proszę o próbę naprawy testów przeprowadzanych przez Github Actions przed czwartkowym spotkaniem.

**Jeśli się to uda**, proszę o zamknięcie tego Issue.
**Jeśli się to nie uda**, proszę o opisanie sytuacji, żebyśmy mogli razem spróbować to naprawić.
