### ISSUE TITLE
MVP - frontend

### ISSUE THREAD

**Issue by mpfmorawski** [mpfmorawski/git-to-know-me#8]
W pierwszym etapie skupiamy się na widoku zalogowanego użytkownika.
Podstawowym zadaniem jest dostosowanie frontu do przewidzianej postaci kafelkowej.

W tym celu chcemy mieć:

- [x]  szablon strony zalogowanego użytkownika
- [x]  kafelek zawierający dane na temat użytkownika (imię, nazwisko, nazwa konta)
- [x]  drugi kafelek zawierający (cokolwiek) - nie muszą to być konkretne dane

**Comment by mpfmorawski** [comment]
Rzeczy do uzupełnienia:

- [ ] resize strony (dodanie bounding boxa, żeby się strona zawsze skalowała)

**Comment by kamilwil** [comment]
> Rzeczy do uzupełnienia:
> 
>     * [ ]  resize strony (dodanie bounding boxa, żeby się strona zawsze skalowała)

Przenoszę do #17
