### ISSUE TITLE
Agregowanie danych

### ISSUE THREAD

**Issue by mpfmorawski** [mpfmorawski/git-to-know-me#9]
Wyciągnięcie podstawowych danych:

- [x] imię
- [x] nazwisko
- [x] nazwa użytkownika
- [x] liczba repozytoriów użytkownik 
- [x] liczba gwiazdek 
- [x] liczba forków
- [ ] liczba repozytoriów organizacji użytkownika (których jest właścicielem)
- [ ] liczba gwiazdek organizacji użytkownika (których jest właścicielem) 
- [ ] liczba forków organizacji użytkownika (których jest właścicielem)

**Comment by pktiuk** [comment]
Kiedy dodasz jakiegoś drafta?

**Comment by jprokopczuk** [comment]
Już jest draft. Zdaje sobie sprawę, że kod trzeba jeszcze mocno dopracować np. poprzez "polepszenie uniwersalności". Obecne rozwiązanie jest mocno napisane na sztywno. Mam kilka pomysłów, które sprawdziły się w innych projektach, ale z chęcią je przedyskutuję.

**Comment by mpfmorawski** [comment]
Rzeczy do uzupełnienia:

- [ ] wysłanie tokena
